### ISSUE TITLE
Feature request: add virtual object for custom properties

### ISSUE THREAD

**Issue by REALMWTH** [code34/oo_vitems.vr#1]
So we can save any variables as properties in array, like it was done in Epoch:
_customproperties = [property_0,property_1,property_n...];

P.S. Great stuff btw!

**Comment by code34** [comment]
hello

i don't know how epoch works but yes array is the simple way to serialize and send data across the network :)

it s a first try implementation. I will add more features if it s used by developpers.

**Comment by REALMWTH** [comment]
I will try to use it to implement item's conditions just like it is working in DayZ SA.
Thumbs up!

**Comment by code34** [comment]
ok, say me what happens and if you required any features. 

I have some ideas but currently i dont priorize this project over others.
